<?php
    namespace Model\Managers;
    
    use App\Manager;
    use App\DAO;

    class PlayerManager extends Manager{

        protected $className = "Model\Entities\Player";
        protected $tableName = "player";

        public function __construct(){
            parent::connect();
        }

        public function modifyPlayerById($id,$nom,$pseudo,$espece,$classe,$description,$planete_origine,$age,
                                        $taille,$poids,$sex,$trait_particulier,$force,$adresse,$intelligence,
                                        $charisme,$mental,$sante,$sante_max,$critique,$stress,$stress_max,
                                        $armure,$chance,$attributsOne,$attributsTwo,$attributsThree,$athletisme,
                                        $baratin,$bricolage,$conduite,$corps_a_corps,$discretion,$erudit,
                                        $informatique,$intimidation,$maitre_du_beat,$negociation,$persuasion,
                                        $science,$soin,$survie,$tir,$vol,$armeOne,$armeTwo,$armeThree,$degatsOne,
                                        $degatsTwo,$degatsThree,$inventaire_1,$inventaire_2,$inventaire_3,
                                        $inventaire_4,$inventaire_5,$inventaire_6,$inventaire_7,$inventaire_8,
                                        $inventaire_9,$inventaire_10,$trait,$description_trait,$deutsch_mark,
                                        $qualiteOne,$qualiteTwo,$qualiteThree,$defautsOne,$defautsTwo,
                                        $defautsThree,$experience){
                parent::connect();
    
                    $sql = "UPDATE ".$this->tableName."
                            SET id_player = :id,
                                nom = :nom,
                                pseudo = :pseudo,
                                espece = :espece,
                                classe = :classe,
                                description = :description ,
                                planete_origine = :planete_origine ,
                                age = :age ,
                                taille = :taille ,
                                poids = :poids,
                                sex = :sex,
                                trait_particulier = :trait_particulier,
                                force = :force,
                                adresse = :adresse,
                                intelligence = :intelligence,
                                charisme = :charisme,
                                mental = :mental,
                                sante = :sante,
                                sante_max = :sante_max,
                                critique = :critique,
                                stress = :stress,
                                stress_max = :stress_max,
                                armure = :armure,
                                chance = :chance,
                                attributsOne = :attributsOne,
                                attributsTwo = :attributsTwo,
                                attributsThree = :attributsThree,
                                athletisme = :athletisme,
                                baratin = :baratin,
                                bricolage = :bricolage,
                                conduite = :conduite,
                                corps_a_corps = :corps_a_corps,
                                discretion = :discretion,
                                erudit = :erudit,
                                informatique = :informatique,
                                intimidation = :intimidation,
                                maitre_du_beat = :maitre_du_beat,
                                negociation = :negociation,
                                persuasion = :persuasion,
                                science = :science,
                                soin = :soin,
                                survie = :survie,
                                tir = :tir,
                                vol = :vol,
                                armeOne = :armeOne,
                                armeTwo = :armeTwo,
                                armeThree = :armeThree,
                                degatsOne = :degatsOne,
                                degatsTwo = :degatsTwo,
                                degatsThree = :degatsThree,
                                inventaire_1 = :inventaire_1,
                                inventaire_2 = :inventaire_2,
                                inventaire_3 = :inventaire_3,
                                inventaire_4 = :inventaire_4,
                                inventaire_5 = :inventaire_5,
                                inventaire_6 = :inventaire_6,
                                inventaire_7 = :inventaire_7,
                                inventaire_8 = :inventaire_8,
                                inventaire_9 = :inventaire_9,
                                inventaire_10 = :inventaire_10,
                                trait = :trait,
                                description_trait = :description_trait,
                                deutsch_mark = :deutsch_mark,
                                qualiteOne = :qualiteOne,
                                qualiteTwo = :qualiteTwo,
                                qualiteThree = :qualiteThree,
                                defautsOne = :defautsOne,
                                defautsTwo = :defautsTwo,
                                defautsThree = :defautsThree,
                                experience = :experience,
                            WHERE id_player = :id";
                        DAO::update($sql, [ 'id' => $id,
                                            'nom' => $nom,
                                            'pseudo' => $pseudo,
                                            'espece' => $espece,
                                            'classe' => $classe,
                                            'description' => $description ,
                                            'planete_origine' => $planete_origine ,
                                            'age' => $age ,
                                            'taille' => $taille ,
                                            'poids' => $poids,
                                            'sex' => $sex,
                                            'trait_particulier' => $trait_particulier,
                                            'force' => $force,
                                            'adresse' => $adresse,
                                            'intelligence' => $intelligence,
                                            'charisme' => $charisme,
                                            'mental' => $mental,
                                            'sante' => $sante,
                                            'sante_max' => $sante_max,
                                            'critique' => $critique,
                                            'stress' => $stress,
                                            'stress_max' => $stress_max,
                                            'armure' => $armure,
                                            'chance' => $chance,
                                            'attributsOne' => $attributsOne,
                                            'attributsTwo' => $attributsTwo,
                                            'attributsThree' => $attributsThree,
                                            'athletisme' => $athletisme,
                                            'baratin' => $baratin,
                                            'bricolage' => $bricolage,
                                            'conduite' => $conduite,
                                            'corps_a_corps' => $corps_a_corps,
                                            'discretion' => $discretion,
                                            'erudit' => $erudit,
                                            'informatique' => $informatique,
                                            'intimidation' => $intimidation,
                                            'maitre_du_beat' => $maitre_du_beat,
                                            'negociation' => $negociation,
                                            'persuasion' => $persuasion,
                                            'science' => $science,
                                            'soin' => $soin,
                                            'survie' => $survie,
                                            'tir' => $tir,
                                            'vol' => $vol,
                                            'armeOne' => $armeOne,
                                            'armeTwo' => $armeTwo,
                                            'armeThree' => $armeThree,
                                            'degatsOne' => $degatsOne,
                                            'degatsTwo' => $degatsTwo,
                                            'degatsThree' => $degatsThree,
                                            'inventaire_1' => $inventaire_1,
                                            'inventaire_2' => $inventaire_2,
                                            'inventaire_3' => $inventaire_3,
                                            'inventaire_4' => $inventaire_4,
                                            'inventaire_5' => $inventaire_5,
                                            'inventaire_6' => $inventaire_6,
                                            'inventaire_7' => $inventaire_7,
                                            'inventaire_8' => $inventaire_8,
                                            'inventaire_9' => $inventaire_9,
                                            'inventaire_10' => $inventaire_10,
                                            'trait' => $trait,
                                            'description_trait' => $description_trait,
                                            'deutsch_mark' => $deutsch_mark,
                                            'qualiteOne' => $qualiteOne,
                                            'qualiteTwo' => $qualiteTwo,
                                            'qualiteThree' => $qualiteThree,
                                            'defautsOne' => $defautsOne,
                                            'defautsTwo' => $defautsTwo,
                                            'defautsThree' => $defautsThree,
                                            'experience' => $experience]);
            }
        }