<?php
    namespace Model\Managers;
    
    use App\Manager;
    use App\DAO;

    class PlayerManager extends Manager{

        protected $className = "Model\Entities\Player";
        protected $tableName = "player";

        public function __construct(){
            parent::connect();
        }

        public function modifyPlayerById($id,$nom,$pseudo,$espece,$classe,$description,$planeteOrigine,$age,
                                        $taille,$poids,$sex,$traitParticulier,$force,$adresse,$intelligence,
                                        $charisme,$mental,$sante,$santeMax,$critique,$stress,$stressMax,
                                        $armure,$chance,$attributsOne,$attributsTwo,$attributsThree,$athletisme,
                                        $baratin,$bricolage,$conduite,$corpsACorps,$discretion,$erudit,
                                        $informatique,$intimidation,$maitreDuBeat,$negociation,$persuasion,
                                        $science,$soin,$survie,$tir,$vol,$armeOne,$armeTwo,$armeThree,$degatsOne,
                                        $degatsTwo,$degatsThree,$inventaire1,$inventaire2,$inventaire3,
                                        $inventaire4,$inventaire5,$inventaire6,$inventaire7,$inventaire8,
                                        $inventaire9,$inventaire10,$trait,$descriptionTrait,$deutschMark,
                                        $qualiteOne,$qualiteTwo,$qualiteThree,$defautsOne,$defautsTwo,
                                        $defautsThree,$experience)
        {
            parent::connect();
    
                $sql = "UPDATE ".$this->tableName."
                            SET nom = :nom,
                                pseudo = :pseudo,
                                espece = :espece,
                                classe = :classe,
                                description = :description ,
                                planeteOrigine = :planeteOrigine ,
                                age = :age ,
                                taille = :taille ,
                                poids = :poids,
                                sex = :sex,
                                traitParticulier = :traitParticulier,
                                force = :force,
                                adresse = :adresse,
                                intelligence = :intelligence,
                                charisme = :charisme,
                                mental = :mental,
                                sante = :sante,
                                santeMax = :santeMax,
                                critique = :critique,
                                stress = :stress,
                                stressMax = :stressMax,
                                armure = :armure,
                                chance = :chance,
                                attributsOne = :attributsOne,
                                attributsTwo = :attributsTwo,
                                attributsThree = :attributsThree,
                                athletisme = :athletisme,
                                baratin = :baratin,
                                bricolage = :bricolage,
                                conduite = :conduite,
                                corpsACorps = :corpsACorps,
                                discretion = :discretion,
                                erudit = :erudit,
                                informatique = :informatique,
                                intimidation = :intimidation,
                                maitreDuBeat = :maitreDuBeat,
                                negociation = :negociation,
                                persuasion = :persuasion,
                                science = :science,
                                soin = :soin,
                                survie = :survie,
                                tir = :tir,
                                vol = :vol,
                                armeOne = :armeOne,
                                armeTwo = :armeTwo,
                                armeThree = :armeThree,
                                degatsOne = :degatsOne,
                                degatsTwo = :degatsTwo,
                                degatsThree = :degatsThree,
                                inventaire1 = :inventaire1,
                                inventaire2 = :inventaire2,
                                inventaire3 = :inventaire3,
                                inventaire4 = :inventaire4,
                                inventaire5 = :inventaire5,
                                inventaire6 = :inventaire6,
                                inventaire7 = :inventaire7,
                                inventaire8 = :inventaire8,
                                inventaire9 = :inventaire9,
                                inventaire10 = :inventaire10,
                                trait = :trait,
                                descriptionTrait = :descriptionTrait,
                                deutschMark = :deutschMark,
                                qualiteOne = :qualiteOne,
                                qualiteTwo = :qualiteTwo,
                                qualiteThree = :qualiteThree,
                                defautsOne = :defautsOne,
                                defautsTwo = :defautsTwo,
                                defautsThree = :defautsThree,
                                experience = :experience,
                            WHERE id_player = :id";
                        DAO::update($sql, [ 'nom' => $nom,
                                            'pseudo' => $pseudo,
                                            'espece' => $espece,
                                            'classe' => $classe,
                                            'description' => $description ,
                                            'planeteOrigine' => $planeteOrigine ,
                                            'age' => $age ,
                                            'taille' => $taille ,
                                            'poids' => $poids,
                                            'sex' => $sex,
                                            'traitParticulier' => $traitParticulier,
                                            'force' => $force,
                                            'adresse' => $adresse,
                                            'intelligence' => $intelligence,
                                            'charisme' => $charisme,
                                            'mental' => $mental,
                                            'sante' => $sante,
                                            'santeMax' => $santeMax,
                                            'critique' => $critique,
                                            'stress' => $stress,
                                            'stressMax' => $stressMax,
                                            'armure' => $armure,
                                            'chance' => $chance,
                                            'attributsOne' => $attributsOne,
                                            'attributsTwo' => $attributsTwo,
                                            'attributsThree' => $attributsThree,
                                            'athletisme' => $athletisme,
                                            'baratin' => $baratin,
                                            'bricolage' => $bricolage,
                                            'conduite' => $conduite,
                                            'corpsACorps' => $corpsACorps,
                                            'discretion' => $discretion,
                                            'erudit' => $erudit,
                                            'informatique' => $informatique,
                                            'intimidation' => $intimidation,
                                            'maitreDuBeat' => $maitreDuBeat,
                                            'negociation' => $negociation,
                                            'persuasion' => $persuasion,
                                            'science' => $science,
                                            'soin' => $soin,
                                            'survie' => $survie,
                                            'tir' => $tir,
                                            'vol' => $vol,
                                            'armeOne' => $armeOne,
                                            'armeTwo' => $armeTwo,
                                            'armeThree' => $armeThree,
                                            'degatsOne' => $degatsOne,
                                            'degatsTwo' => $degatsTwo,
                                            'degatsThree' => $degatsThree,
                                            'inventaire1' => $inventaire1,
                                            'inventaire2' => $inventaire2,
                                            'inventaire3' => $inventaire3,
                                            'inventaire4' => $inventaire4,
                                            'inventaire5' => $inventaire5,
                                            'inventaire6' => $inventaire6,
                                            'inventaire7' => $inventaire7,
                                            'inventaire8' => $inventaire8,
                                            'inventaire9' => $inventaire9,
                                            'inventaire10' => $inventaire10,
                                            'trait' => $trait,
                                            'descriptionTrait' => $descriptionTrait,
                                            'deutschMark' => $deutschMark,
                                            'qualiteOne' => $qualiteOne,
                                            'qualiteTwo' => $qualiteTwo,
                                            'qualiteThree' => $qualiteThree,
                                            'defautsOne' => $defautsOne,
                                            'defautsTwo' => $defautsTwo,
                                            'defautsThree' => $defautsThree,
                                            'experience' => $experience]);
        }
    }